name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Si attiva quando pushi su main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Installa dipendenze
        run: npm ci

      - name: Build del progetto con variabili d'ambiente
        run: npm run build
        env:
          # Qui GitHub inietta i segreti che hai impostato prima trasformandoli in variabili per la build
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Carica l'artefatto della build
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Se usi Vite la cartella è 'dist', per altri framework potrebbe essere 'build' o '.'

      - name: Deploy su GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4